@startuml
!define RECTANGLE class
skinparam rectangle {
  BackgroundColor #DDDDDD
  BorderColor #000000
}

rectangle API_Gateway {
  [API Gateway] <<Gateway>>
}

rectangle Auth_Service {
  [Auth Service] <<Service>>
}

rectangle Player_Service {
  [Player Service] <<Service>>
}


rectangle Database {
  [User DB] <<Database>>
  [Player DB] <<Database>>
}

API_Gateway -right-> Auth_Service: authenticate
API_Gateway -right-> Player_Service: manage players

Player_Service --> Auth_Service: request user info

Auth_Service --> [User DB]: manage user auth data
Player_Service --> [Player DB]: manage player data

@enduml
